[package]
name = "pathfinder-update"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
pathfinder-common = { path = "../common" }
reqwest = "0.11.4"
semver = "1.0.7"
serde = { version = "1.0.130", features = ["derive"] }
tokio = "1.11.0"
tracing = "0.1.31"

[dev-dependencies]
assert_matches = "1.5.0"

[build-dependencies]
vergen = { version = "7", default-features = false, features = ["git"] }
