[profile.stripdebuginfo]
# Used by CI to lower binary size for test artifacts.
inherits = "test"
strip = "debuginfo"

[workspace]
members = [
    "crates/build",
    "crates/common",
    "crates/ethereum",
    "crates/gateway-test-fixtures",
    "crates/gateway-types",
    "crates/load-test",
    "crates/pathfinder",
    "crates/retry",
    "crates/serde",
    "crates/stark_curve",
    "crates/stark_hash",
    "crates/update",
]
resolver = "2"
