[profile.stripdebuginfo]
# Used by CI to lower binary size for test artifacts.
inherits = "test"
strip = "debuginfo"

[workspace]
members = [
    "crates/load-test",
    "crates/pathfinder",
    "crates/stark_curve",
    "crates/stark_hash",
]
resolver = "2"
