[package]
name = "pathfinder-merkle-tree"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
bitvec = "0.20.4"
pathfinder-common = { path = "../common" }
pathfinder-storage = { path = "../storage" }
rand = "0.8"
rusqlite = { version = "0.27.0", features = ["bundled"] }
stark_hash = { path = "../stark_hash" }

[dev-dependencies]
hex-literal = "0.3"
pretty_assertions = "1.0.0"
