[package]
authors = [
    "Mirko von Leipzig <mirko.vonleipzig@gmail.com>",
    "Krzysztof Lis <klis33@gmail.com>",
]
name = "pathfinder"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pathfinder_lib"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.44"
bigdecimal = { version = "0.3.0", features = ["serde"] }
# paritys scale codec locks us here
bitvec = "0.20.4"
clap = "2.33.3"
enum-iterator = "0.7.0"
# Use our fork of ff. ff currently causes a bitvec-funty clash with our ethereum deps.
# We've modified ff to not rely on bitvec (note that ff features are broken: https://github.com/zkcrypto/ff/issues/69).
# We can use normal ff once it and `ethabi` (via `web3`) play nice.
ff = { git = "https://github.com/eqlabs/ff", branch = "derive_bitvec", default-features = false, features = [
    "derive",
    "alloc",
] }
hex = "0.4.3"
home = "0.5.3"
jsonrpsee = { version = "0.6.1", features = ["full"] }
lazy_static = "1.4.0"
reqwest = { version = "0.11.4", features = ["json"] }
rusqlite = { version = "0.26.1", features = ["bundled"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_with = "1.9.4"
tokio = "1.11.0"
toml = "0.5.8"
web3 = "0.17.0"

[dev-dependencies]
assert_matches = "1.5.0"
criterion = "0.3"
pretty_assertions = "1.0.0"

[[bench]]
name = "pedersen"
harness = false
