name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # An Ethereum access point is required for some L1 StarkNet contract tests.
      # This sets it to secret values stored in the repository, which prevents
      # leaking it in code.
      PATHFINDER_ETHEREUM_HTTP_GOERLI_URL:       ${{ secrets.PATHFINDER_ETHEREUM_HTTP_GOERLI_URL }}
      PATHFINDER_ETHEREUM_HTTP_GOERLI_PASSWORD:  ${{ secrets.PATHFINDER_ETHEREUM_HTTP_GOERLI_PASSWORD }}
      PATHFINDER_ETHEREUM_HTTP_MAINNET_URL:      ${{ secrets.PATHFINDER_ETHEREUM_HTTP_MAINNET_URL }}
      PATHFINDER_ETHEREUM_HTTP_MAINNET_PASSWORD: ${{ secrets.PATHFINDER_ETHEREUM_HTTP_MAINNET_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: |
          timeout 5m cargo test -p pathfinder -- --skip rpc::tests --skip sequencer::tests
          timeout 3m cargo test -p pedersen --benches
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy --workspace --all-targets -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt --all -- --check

  dep-sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo install cargo-sort
          cargo sort --check --workspace

  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Prepare py/
        run: |
          cd py
          pip install --upgrade pip
          pip install --requirement requirements-dev.txt
          pip install cairo-lang==0.7.0

      - name: Test (python)
        run: |
          cd py
          pytest

      - name: Formatting (python)
        run: |
          cd py
          black --check src/

      - name: Lints (python)
        run: |
          cd py
          flake8 src/
