name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile_tests:
    name: Compile pathfinder tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
        with:
          mold-version: 1.4.1
          make-default: false
      - name: Enable mold
        run: |
          mkdir -p $HOME/.cargo
          cat << EOF >> $HOME/.cargo/config.toml
          [target.x86_64-unknown-linux-gnu]
          linker = "/usr/bin/clang"
          rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
          EOF

          cat $HOME/.cargo/config.toml
      - uses: Swatinem/rust-cache@v2
        with:
          key: "mold"

      - name: Compile tests
        id: compile-tests
        # Note:
        # - profile changed because otherwise some test binaries are 100MB+ in size with pathfinder_lib over 1GB
        # - package pathfinder produces two test binaries: pathfinder & pathfinder_lib
        run: |
          cargo test --no-run --locked --profile stripdebuginfo --message-format=json \
            -p pathfinder -p pathfinder-ethereum -p pathfinder-serde -p starknet-gateway-types \
            | jq -r 'select(.reason=="compiler-artifact" and .target.test==true and .executable) | .executable' \
            | xargs -I '{}' bash -c 'file={}; mv ${file} $(basename ${file::(-17)})'

      - name: Archive test binary pathfinder
        uses: actions/upload-artifact@v3
        with:
          name: test-binary-pathfinder
          path: pathfinder
          if-no-files-found: error

      - name: Archive test binary pathfinder_ethereum
        uses: actions/upload-artifact@v3
        with:
          name: test-binary-pathfinder-ethereum
          path: pathfinder_ethereum
          if-no-files-found: error

      - name: Archive test binary pathfinder_lib
        uses: actions/upload-artifact@v3
        with:
          name: test-binary-pathfinder-lib
          path: pathfinder_lib
          if-no-files-found: error

      - name: Archive test binary pathfinder_serde
        uses: actions/upload-artifact@v3
        with:
          name: test-binary-pathfinder-serde
          path: pathfinder_serde
          if-no-files-found: error

      - name: Archive test binary starknet_gateway_types
        uses: actions/upload-artifact@v3
        with:
          name: test-binary-starknet-gateway-types
          path: starknet_gateway_types
          if-no-files-found: error

  # Tests with stripped test binaries
  test_pathfinder:
    name: pathfinder (binary) tests
    needs: compile_tests
    runs-on: ubuntu-latest
    steps:       
      # Fetch the test binary artifact
      - uses: actions/download-artifact@v3
        with:
          name: test-binary-pathfinder
      # Archiving removes the file permissions
      - name: Fix file permissions
        run: chmod +x pathfinder

      - name: Execute tests
        run: ./pathfinder

  test_pathfinder_ethereum:
    name: pathfinder-ethereum tests
    needs: compile_tests
    runs-on: ubuntu-latest
    steps:       
      # Fetch the test binary artifact
      - uses: actions/download-artifact@v3
        with:
          name: test-binary-pathfinder-ethereum
      # Archiving removes the file permissions
      - name: Fix file permissions
        run: chmod +x pathfinder_ethereum

      - name: Execute tests
        run: ./pathfinder_ethereum

  test_pathfinder_lib:
    name: pathfinder_lib tests (excludes L1)
    needs: compile_tests
    runs-on: ubuntu-latest
    steps:
      # Required for the python environment
      - uses: actions/checkout@v3

      # Fetch the test binary artifact
      - uses: actions/download-artifact@v3
        with:
          name: test-binary-pathfinder-lib
      # Archiving removes the file permissions
      - name: Fix file permissions
        run: chmod +x pathfinder_lib

      - uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: 'py/requirements*.txt'
      # Workaround for setup-python issue #330 (https://github.com/actions/setup-python/issues/330)
      - uses: actions/cache@v3
        id: python_cache
        with:
          path: ${{ env.pythonLocation }}/**/site-packages
          key: site-packages-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('py/requirements*.txt') }}
      - run: pip install -e py/.

      - name: Execute tests
        run: "./pathfinder_lib --skip ethereum::"

  test_alchemy:
    name: pathfinder_lib tests (alchemy)
    needs: compile_tests
    runs-on: ubuntu-latest
    steps:       
      # Fetch the test binary artifact
      - uses: actions/download-artifact@v3
        with:
          name: test-binary-pathfinder-lib
      # Archiving removes the file permissions
      - name: Fix file permissions
        run: chmod +x pathfinder_lib

      - name: Execute tests
        run: |
          PATHFINDER_ETHEREUM_HTTP_GOERLI_URL=${{ secrets.ALCHEMY_GOERLI_URL }} \
            PATHFINDER_ETHEREUM_HTTP_GOERLI_PASSWORD=${{ secrets.ALCHEMY_GOERLI_PASSWORD }} \
            PATHFINDER_ETHEREUM_HTTP_MAINNET_URL=${{ secrets.ALCHEMY_MAINNET_URL }} \
            PATHFINDER_ETHEREUM_HTTP_MAINNET_PASSWORD=${{ secrets.ALCHEMY_MAINNET_PASSWORD }} \
            timeout 3m ./pathfinder_lib ethereum::

  test_infura:
    name: pathfinder_lib tests (infura)
    needs: compile_tests
    runs-on: ubuntu-latest
    steps:       
      # Fetch the test binary artifact
      - uses: actions/download-artifact@v3
        with:
          name: test-binary-pathfinder-lib
      # Archiving removes the file permissions
      - name: Fix file permissions
        run: chmod +x pathfinder_lib

      - name: Execute tests
        run: |
          PATHFINDER_ETHEREUM_HTTP_GOERLI_URL=${{ secrets.INFURA_GOERLI_URL }} \
            PATHFINDER_ETHEREUM_HTTP_GOERLI_PASSWORD=${{ secrets.INFURA_GOERLI_PASSWORD }} \
            PATHFINDER_ETHEREUM_HTTP_MAINNET_URL=${{ secrets.INFURA_MAINNET_URL }} \
            PATHFINDER_ETHEREUM_HTTP_MAINNET_PASSWORD=${{ secrets.INFURA_MAINNET_PASSWORD }} \
            timeout 3m ./pathfinder_lib ethereum::

  test_pathfinder_serde:
    name: pathfinder-serde tests
    needs: compile_tests
    runs-on: ubuntu-latest
    steps:       
      # Fetch the test binary artifact
      - uses: actions/download-artifact@v3
        with:
          name: test-binary-pathfinder-serde
      # Archiving removes the file permissions
      - name: Fix file permissions
        run: chmod +x pathfinder_serde

      - name: Execute tests
        run: ./pathfinder_serde

  test_starknet_gateway_types:
    name: starknet-gateway-types tests
    needs: compile_tests
    runs-on: ubuntu-latest
    steps:       
      # Fetch the test binary artifact
      - uses: actions/download-artifact@v3
        with:
          name: test-binary-starknet-gateway-types
      # Archiving removes the file permissions
      - name: Fix file permissions
        run: chmod +x starknet_gateway_types

      - name: Execute tests
        run: ./starknet_gateway_types

  # Tests with unstripped test binaries
  test_pathfinder_common:
    name: pathfinder-common tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: tests
        run: cargo test -p pathfinder-common --all-targets --locked

  test_pathfinder_retry:
    name: pathfinder-retry tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: tests
        run: cargo test -p pathfinder-retry --all-targets --locked

  test_stark_curve:
    name: stark_curve tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: tests
        run: cargo test -p stark_curve --all-targets --locked

  test_stark_hash:
    name: stark_hash tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: tests
        run: cargo test -p stark_hash --all-targets --locked

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --all-targets --locked -- -D warnings -D rust_2018_idioms

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --no-deps --document-private-items

  dep-sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo install cargo-sort
          cargo sort --check --workspace

  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Prepare py/
        run: |
          cd py
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Test (python)
        run: |
          source py/.venv/bin/activate
          cd py
          pytest

      - name: Formatting (python)
        run: |
          source py/.venv/bin/activate
          cd py
          black --check .

      - name: Lints (python)
        run: |
          source py/.venv/bin/activate
          cd py
          flake8 src/ tests/ tools/

      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
        with:
          mold-version: 1.4.1
          make-default: false
      - name: Enable mold
        run: |
          mkdir -p $HOME/.cargo
          cat << EOF >> $HOME/.cargo/config.toml
          [target.x86_64-unknown-linux-gnu]
          linker = "/usr/bin/clang"
          rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
          EOF

          cat $HOME/.cargo/config.toml

      - uses: Swatinem/rust-cache@v2
        with:
          key: "mold"
      - name: Integration (rust)
        run: |
          source py/.venv/bin/activate
          cargo test --no-run -p pathfinder
          timeout 5m cargo test -p pathfinder -- cairo::ext_py --ignored

  fuzz_targets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: rui314/setup-mold@v1
        with:
          mold-version: 1.4.1
          make-default: false
      - name: Enable mold
        run: |
          mkdir -p $HOME/.cargo
          cat << EOF >> $HOME/.cargo/config.toml
          [target.x86_64-unknown-linux-gnu]
          linker = "/usr/bin/clang"
          rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
          EOF

          cat $HOME/.cargo/config.toml
      - uses: Swatinem/rust-cache@v2
        with:
          key: "mold"
      - run: cargo install cargo-fuzz
      - name: stark_hash
        run: cargo fuzz build
        working-directory: crates/stark_hash
