name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # An Ethereum access point is required for some L1 StarkNet contract tests.
      # This sets it to secret values stored in the repository, which prevents
      # leaking it in code.
      STARKNET_ETHEREUM_WEBSOCKET_URL: ${{ secrets.STARKNET_ETHEREUM_WEBSOCKET_URL }}
      STARKNET_ETHEREUM_PASSWORD: ${{ secrets.STARKNET_ETHEREUM_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: timeout 5m cargo test --workspace --all-features --all-targets
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy --workspace --all-targets -- -D warnings -A dead-code

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt --all -- --check

  dep-sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo install cargo-sort
          cargo sort --check --workspace

  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Prepare py/
        run: |
          cd py
          pip install --upgrade pip
          pip install --requirement requirements-dev.txt
          pip install cairo-lang==0.6.2

      - name: Test (python)
        run: |
          cd py
          pytest

      - name: Formatting (python)
        run: |
          cd py
          black --check src/

      - name: Lints (python)
        run: |
          cd py
          flake8 src/
